[tox]
isolated_build = True
envlist = py,check


[testenv]
# means we'll run the equivalent of `pip install .[dev]`, also installing pytest
# and the linters from pyproject.toml
extras = dev

# Non-interactive backend for doctests
setenv =
    MPLBACKEND = Agg

# Enable package caching
package_cache = .tox/cache

# Run doctests and coverage for the package.
commands =
    pytest -n auto --doctest-modules src/pgam_clean/
    pytest -n auto --cov=pgam_clean --cov-config=pyproject.toml --cov-report=xml

[testenv:fix]
skip_install = True
deps =
    black
    isort
    flake8
    ruff
commands =
    black src
    isort src --profile=black
    black tests
    isort tests --profile=black
    flake8 --config={toxinidir}/tox.ini src
    ruff check --fix src/pgam_clean
    black examples
    isort examples --profile=black

[testenv:check]
skip_install = True
deps =
    black
    isort
    flake8
    ruff
commands =
    black --check src
    isort --check src --profile=black
    black --check tests
    isort --check tests --profile=black
    flake8 --config={toxinidir}/tox.ini src
    ruff check src/pgam_clean
    black --check examples
    isort --check examples --profile=black

[gh-actions]
python =
       3.12: py312
       3.13: py313
       3.14: py314


[flake8]
max-complexity = 10
max-line-length = 120
exclude = '''
    ((\.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.md
    | \.toml
    | \.cfg
    | \.txt
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | examples
    | __init__.py  # Exclude __init__.py files
    ))'''
extend-ignore = W605, E203, DAR, F722
